### ISSUE TITLE
Webpack Dev Mode static assets access issue over HTTPS.

### ISSUE THREAD

**Issue by Panoplos** [casoetan/react-horizon#4]
I ran into an issue where your configuration of `WebpackDevServer` does not utilize the certs that are created for the project. This results in `net::ERR_INSECURE_RESPONSE` error when attempting to access the static assets served by Webpack on `localhost:9095` as follows:
<img width="1438" alt="screen shot 2017-03-30 at 1 08 13 am" src="https://cloud.githubusercontent.com/assets/2549985/24464728/b584a330-14e5-11e7-81f1-2dc83909f6cc.png">

I fixed this by changing `webpack-config-client-dev.js` line 38 to:

```js
    https: {
      cert: fs.readFileSync(path.join(serverPath, "horizon-cert.pem")),
      key:  fs.readFileSync(path.join(serverPath, "horizon-key.pem")),
    },
```
And adding:

```js
const webpack = require('webpack');
const defaultConfig = require('./webpack.config.client');
const serverPath = path.join(__dirname, '../../source/server')
```
at the top of the file.

**Comment by casoetan** [comment]
I've hardly had time to maintain it. I would be happy if you can submit a PR

PS. Do you mind becoming a collaborator here?

**Comment by Panoplos** [comment]
I was hoping for a stable boilerplate app on this stack so I could get rolling with my own project. I'll keep working with the code to get familiar with all the modules. If I come up some some good fixes, will contribute, so yeah, you can add me as a collaborator.
