### ISSUE TITLE
Socket Cluster connection issues...

### ISSUE THREAD

**Issue by Panoplos** [casoetan/react-horizon#5]
After getting the app to finally run, I am seeing the following errors in the browser console:

<img width="1437" alt="screen shot 2017-03-30 at 1 16 59 am" src="https://cloud.githubusercontent.com/assets/2549985/24465053/c63c86ec-14e6-11e7-8089-3f8afc0892dd.png">

The problem is that it is trying to connect to `localhost:8000`, but there is no server running on that port.

Also the timeout on login, etc.... Just seems overall buggy.

**Comment by casoetan** [comment]
The error you are getting is because you have not launched remotedev. Run 
```sh
npm run remotedev
```
to start the remotedev server, then launch the RemoteDev app if you have it installed. 

This allows you monitor redux actions in RemoteDev.

**Comment by Panoplos** [comment]
There you go! Fixed... Maybe RemoteDev server should be run as part of the dev startup? I am new to Redux, so this was really not obvious. Maybe others would benefit from it. ;^)

**Comment by casoetan** [comment]
Happy you got it sorted out.

You can get more info here [RemoteDev App Github](https://github.com/zalmoxisus/remotedev-app)

You can download the app from the Chrome Store [RemoteDev App](https://chrome.google.com/webstore/detail/remotedev/faicmgpfiaijcedapokpbdejaodbelph)

**Comment by casoetan** [comment]
I will add this to the doc. Can I close this?
